name: Hygiene
permissions:
  contents: read
  pull-requests: write
on:
  workflow_dispatch: {}
  pull_request: {}
jobs:
  Lint:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install tools
        run: brew install swiftformat swiftlint
      - name: SwiftFormat lint
        run: swiftformat --lint .
      - name: SwiftLint strict
        run: swiftlint --strict --quiet --reporter github-actions-logging
